// JobFrontendApp/JobWebApp/frontend_NextJs/src/components/jobs/JobCard.tsx
'use client';

import { Button, Divider, Text } from '@mantine/core';
import { IconBookmark, IconBookmarkFilled, IconCalendarMonth, IconClockHour3 } from '@tabler/icons-react';
import Link from 'next/link';
import CompanyLogo from '@/components/shared/CompanyLogo';
import { formatInterviewTime, timeAgo } from '@/lib/utils/date';
import { useAppStore } from '@/store/app-store-provider';
import type { Job } from '@/types';

export type JobCardVariant = 'default' | 'applied' | 'saved' | 'offered' | 'interviewing';

const TIME_LABEL: Record<JobCardVariant, string> = {
  default: 'Posted',
  saved: 'Posted',
  applied: 'Applied',
  interviewing: 'Applied',
  offered: 'Interviewed',
};

/** Job summary card used by Find Jobs, Recommended Jobs, Company Jobs and Job History. */
export default function JobCard({ job, variant = 'default' }: { job: Job; variant?: JobCardVariant }) {
  const saved = useAppStore((s) => s.profile?.savedJobs?.includes(job.id) ?? false);
  const toggleSavedJob = useAppStore((s) => s.toggleSavedJob);
  const userId = useAppStore((s) => s.user?.id);
  const interviewTime = job.applicants?.find((a) => a.applicantId === userId)?.interviewTime;
  const Bookmark = saved ? IconBookmarkFilled : IconBookmark;

  return (
    <article
      data-aos="fade-up"
      className="flex w-72 flex-col gap-3 rounded-xl bg-mine-shaft-900 p-4 transition duration-300 ease-in-out hover:shadow-[0_0_5px_1px] hover:shadow-bright-sun-400 max-sm:w-full"
    >
      <div className="flex justify-between">
        <div className="flex items-center gap-2">
          <div className="shrink-0 rounded-md bg-mine-shaft-800 p-2">
            <CompanyLogo name={job.company} />
          </div>
          <div className="flex flex-col gap-1">
            <div className="font-semibold">{job.jobTitle}</div>
            <div className="text-xs text-mine-shaft-300">
              <Link className="hover:text-mine-shaft-200" href={`/company/${encodeURIComponent(job.company)}`}>
                {job.company}
              </Link>{' '}
              &bull; {job.applicants?.length ?? 0} Applicants
            </div>
          </div>
        </div>
        <button type="button" className="h-fit" aria-label={saved ? 'Remove from saved jobs' : 'Save job'} onClick={() => toggleSavedJob(job.id)}>
          <Bookmark className={saved ? 'text-bright-sun-400' : 'text-mine-shaft-300 hover:text-bright-sun-400'} stroke={1.5} />
        </button>
      </div>

      <div className="flex flex-wrap gap-2 [&>div]:rounded-lg [&>div]:bg-mine-shaft-800 [&>div]:p-2 [&>div]:py-1 [&>div]:text-xs [&>div]:text-bright-sun-400">
        <div>{job.experience}</div>
        <div>{job.jobType}</div>
        <div>{job.location}</div>
      </div>

      <Text className="text-justify text-xs! text-mine-shaft-300!" lineClamp={3}>
        {job.about}
      </Text>

      <Divider color="mineShaft.7" size="xs" />
      <div className="flex justify-between">
        <div className="font-semibold text-mine-shaft-200">&#8377;{job.packageOffered} LPA</div>
        <div className="flex items-center gap-1 text-xs text-mine-shaft-400">
          <IconClockHour3 className="h-5 w-5" stroke={1.5} />
          {TIME_LABEL[variant]} {timeAgo(job.postTime)}
        </div>
      </div>

      {(variant === 'offered' || variant === 'interviewing') && <Divider color="mineShaft.7" size="xs" />}
      {variant === 'offered' && (
        <div className="flex gap-2">
          <Button color="brightSun.4" variant="outline" fullWidth>
            Accept
          </Button>
          <Button color="brightSun.4" variant="light" fullWidth>
            Reject
          </Button>
        </div>
      )}
      {variant === 'interviewing' && (
        <div className="flex items-center gap-1 text-sm">
          <IconCalendarMonth className="h-5 w-5 text-bright-sun-400" stroke={1.5} />
          {interviewTime ? formatInterviewTime(interviewTime) : 'Interview being scheduled'}
        </div>
      )}

      <Button component={Link} href={`/jobs/${job.id}`} className="mt-auto" fullWidth color="brightSun.4" variant="light">
        View Job
      </Button>
    </article>
  );
}

// JobFrontendApp/JobWebApp/frontend_Angular/src/app/shared/components/job-card/job-card.ts
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Job } from '../../../core/models';
import { ProfileStore } from '../../../core/state/profile.store';
import { SessionStore } from '../../../core/state/session.store';
import { ImgFallbackDirective } from '../../directives/img-fallback.directive';
import { InterviewTimePipe, TimeAgoPipe } from '../../pipes/date.pipes';
import { Icon } from '../../ui/icon/icon';

export type JobCardVariant = 'default' | 'applied' | 'saved' | 'offered' | 'interviewing';

/** Job summary card used by Find Jobs, Recommended Jobs, Company Jobs and Job History. */
@Component({
  selector: 'app-job-card',
  imports: [RouterLink, Icon, TimeAgoPipe, InterviewTimePipe, ImgFallbackDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: 'block w-72 max-sm:w-full', 'data-aos': 'fade-up' },
  template: `
    @let j = job();
    <article class="card h-full">
      <div class="flex justify-between gap-2">
        <div class="flex items-center gap-2">
          <div class="logo-box">
            <img class="h-7 w-7 object-contain" [src]="'/Icons/' + j.company + '.png'" alt="" appImgFallback />
          </div>
          <div class="flex flex-col gap-1">
            <div class="font-semibold">{{ j.jobTitle }}</div>
            <div class="text-xs text-mine-shaft-300">
              <a class="hover:text-mine-shaft-200" [routerLink]="['/company', j.company]">{{ j.company }}</a>
              &bull; {{ j.applicants?.length ?? 0 }} Applicants
            </div>
          </div>
        </div>
        <button
          type="button"
          class="h-fit"
          [class]="saved() ? 'text-bright-sun-400' : 'text-mine-shaft-300 hover:text-bright-sun-400'"
          [attr.aria-label]="saved() ? 'Remove from saved jobs' : 'Save job'"
          (click)="profileStore.toggleSavedJob(j.id)"
        >
          <app-icon [name]="saved() ? 'bookmark-filled' : 'bookmark'" [size]="22" [stroke]="1.5" />
        </button>
      </div>

      <div class="flex flex-wrap gap-2">
        <span class="chip">{{ j.experience }}</span>
        <span class="chip">{{ j.jobType }}</span>
        <span class="chip">{{ j.location }}</span>
      </div>

      <p class="line-clamp-3 text-justify text-xs! text-mine-shaft-300">{{ j.about }}</p>

      <hr class="divider" />
      <div class="flex justify-between gap-2">
        <div class="font-semibold text-mine-shaft-200">&#8377;{{ j.packageOffered }} LPA</div>
        <div class="flex items-center gap-1 text-xs text-mine-shaft-400">
          <app-icon name="clock-hour-3" [size]="18" [stroke]="1.5" />
          {{ timeLabel() }} {{ j.postTime | timeAgo }}
        </div>
      </div>

      @if (variant() === 'offered' || variant() === 'interviewing') {
        <hr class="divider" />
      }
      @if (variant() === 'offered') {
        <div class="flex gap-2">
          <button type="button" class="btn btn-outline btn-block">Accept</button>
          <button type="button" class="btn btn-light btn-block">Reject</button>
        </div>
      }
      @if (variant() === 'interviewing') {
        <div class="flex items-center gap-1 text-sm">
          <app-icon name="calendar-month" [size]="18" class="text-bright-sun-400" />
          @if (interviewTime(); as time) {
            {{ time | interviewTime }}
          } @else {
            Interview being scheduled
          }
        </div>
      }

      <a class="btn btn-light btn-block mt-auto" [routerLink]="['/jobs', j.id]">View Job</a>
    </article>
  `,
})
export class JobCard {
  protected readonly profileStore = inject(ProfileStore);
  private readonly session = inject(SessionStore);

  readonly job = input.required<Job>();
  readonly variant = input<JobCardVariant>('default');

  protected readonly saved = computed(() => this.profileStore.savedJobs().includes(this.job().id));
  /** The logged-in applicant's interview slot for this job, if one is scheduled. */
  protected readonly interviewTime = computed(
    () => this.job().applicants?.find((a) => a.applicantId === this.session.userId())?.interviewTime ?? null,
  );
  protected readonly timeLabel = computed(() => {
    switch (this.variant()) {
      case 'applied':
      case 'interviewing':
        return 'Applied';
      case 'offered':
        return 'Interviewed';
      default:
        return 'Posted';
    }
  });
}
