// JobFrontendApp/JobWebApp/frontend_NextJs/src/components/header/ProfileMenu.tsx
'use client';

import { Avatar, Menu, Switch, rem, useMantineColorScheme } from '@mantine/core';
import {
  IconFileText,
  IconLogout2,
  IconMessageCircle,
  IconMoon,
  IconMoonStars,
  IconSun,
  IconUserCircle,
} from '@tabler/icons-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { persistTheme } from '@/lib/auth/session';
import { pictureSrc } from '@/lib/utils/file';
import { useAppStore } from '@/store/app-store-provider';

const iconStyle = { width: rem(14), height: rem(14) };

export default function ProfileMenu() {
  const router = useRouter();
  const user = useAppStore((s) => s.user);
  const profile = useAppStore((s) => s.profile);
  const logout = useAppStore((s) => s.logout);
  const { colorScheme, setColorScheme } = useMantineColorScheme();
  const [opened, setOpened] = useState(false);
  const isLight = colorScheme === 'light';

  const toggleTheme = (light: boolean) => {
    const scheme = light ? 'light' : 'dark';
    document.documentElement.classList.toggle('light-theme', light); // Tailwind mine-shaft colours
    setColorScheme(scheme); // Mantine components
    persistTheme(scheme); // cookie -> correct theme on the next server render
  };

  const handleLogout = () => {
    logout();
    router.push('/');
    router.refresh();
  };

  return (
    <Menu shadow="md" width={200} opened={opened} onChange={setOpened}>
      <Menu.Target>
        <button type="button" className="flex items-center gap-2">
          <span className="max-xs:hidden">{user?.name}</span>
          <Avatar src={pictureSrc(profile?.picture)} alt="Your avatar" />
        </button>
      </Menu.Target>

      <Menu.Dropdown>
        <Menu.Item component={Link} href="/profile" leftSection={<IconUserCircle style={iconStyle} />}>
          Profile
        </Menu.Item>
        <Menu.Item leftSection={<IconMessageCircle style={iconStyle} />}>Messages</Menu.Item>
        <Menu.Item leftSection={<IconFileText style={iconStyle} />}>Resume</Menu.Item>
        <Menu.Item
          closeMenuOnClick={false}
          onClick={() => toggleTheme(!isLight)}
          leftSection={<IconMoon style={iconStyle} />}
          rightSection={
            <Switch
              size="sm"
              color="dark"
              checked={isLight}
              onChange={(e) => toggleTheme(e.currentTarget.checked)}
              onClick={(e) => e.stopPropagation()}
              onLabel={<IconSun style={iconStyle} stroke={2.5} color="yellow" />}
              offLabel={<IconMoonStars style={iconStyle} stroke={2.5} color="cyan" />}
              aria-label="Toggle light mode"
            />
          }
        >
          {isLight ? 'Light Mode' : 'Dark Mode'}
        </Menu.Item>
        <Menu.Divider />
        <Menu.Item onClick={handleLogout} color="red" leftSection={<IconLogout2 style={iconStyle} />}>
          Logout
        </Menu.Item>
      </Menu.Dropdown>
    </Menu>
  );
}

// JobFrontendApp/JobWebApp/frontend_Angular/src/app/layout/header/profile-menu/profile-menu.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { ThemeService } from '../../../core/services/theme.service';
import { ProfileStore } from '../../../core/state/profile.store';
import { SessionStore } from '../../../core/state/session.store';
import { ClickOutsideDirective } from '../../../shared/directives/click-outside.directive';
import { PicturePipe } from '../../../shared/pipes/picture.pipe';
import { Icon } from '../../../shared/ui/icon/icon';

@Component({
  selector: 'app-profile-menu',
  imports: [RouterLink, Icon, PicturePipe, ClickOutsideDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="relative" (appClickOutside)="open.set(false)">
      <button type="button" class="flex items-center gap-2" [attr.aria-expanded]="open()" aria-haspopup="menu" (click)="open.set(!open())">
        <span class="max-xs:hidden">{{ session.user()?.name }}</span>
        <img class="h-9 w-9 rounded-full object-cover" [src]="profileStore.profile()?.picture | picture" alt="Your avatar" />
      </button>

      @if (open()) {
        <div class="dropdown right-0 w-52 py-1" role="menu">
          <a routerLink="/profile" class="dropdown-item" role="menuitem" (click)="open.set(false)">
            <app-icon name="user-circle" [size]="16" /> Profile
          </a>
          <button type="button" class="dropdown-item" role="menuitem">
            <app-icon name="message-circle" [size]="16" /> Messages
          </button>
          <button type="button" class="dropdown-item" role="menuitem">
            <app-icon name="file-text" [size]="16" /> Resume
          </button>
          <button type="button" class="dropdown-item justify-between" role="menuitemcheckbox" [attr.aria-checked]="isLight()" (click)="theme.toggle()">
            <span class="flex items-center gap-2"><app-icon name="moon" [size]="16" /> {{ isLight() ? 'Light Mode' : 'Dark Mode' }}</span>
            <span class="relative inline-flex h-5 w-9 items-center rounded-full transition" [class]="isLight() ? 'bg-mine-shaft-200' : 'bg-mine-shaft-700'">
              <span class="absolute flex h-4 w-4 items-center justify-center rounded-full bg-white transition-transform" [class]="isLight() ? 'translate-x-[18px]' : 'translate-x-0.5'">
                <app-icon [name]="isLight() ? 'sun' : 'moon-stars'" [size]="11" [stroke]="2.5" [class]="isLight() ? 'text-yellow-500' : 'text-cyan-600'" />
              </span>
            </span>
          </button>
          <hr class="divider my-1" />
          <button type="button" class="dropdown-item text-red-500!" role="menuitem" (click)="logout()">
            <app-icon name="logout-2" [size]="16" /> Logout
          </button>
        </div>
      }
    </div>
  `,
})
export class ProfileMenu {
  private readonly router = inject(Router);
  protected readonly session = inject(SessionStore);
  protected readonly profileStore = inject(ProfileStore);
  protected readonly theme = inject(ThemeService);
  protected readonly open = signal(false);

  protected isLight(): boolean {
    return this.theme.scheme() === 'light';
  }

  protected logout(): void {
    this.open.set(false);
    this.session.logout();
    this.router.navigateByUrl('/');
  }
}
